### ISSUE TITLE
MacType 渲染导致桌面字体变黑，图标多个了白色背景

### ISSUE THREAD

**Issue by duanluan** [coodesker/coodesker-desktop#1]
在 MacType 安装目录 /ini/Default.ini 的 [ExcludeModule] 块下面添加 CooDesker.exe 了，有时候好有时候不好。

**Comment by coodesker** [comment]
> 在 MacType 安装目录 /ini/Default.ini 的 [ExcludeModule] 块下面添加 CooDesker.exe 了，有时候好有时候不好。

您好，谢谢您的反馈，我们工程师正在解决这个问题

**Comment by coodesker** [comment]
v1.0.0.5 fixed this issue
