### ISSUE TITLE
扫描隐私问题

### ISSUE THREAD

**Issue by gdzjy** [coodesker/coodesker-desktop#102]
自从用了coodesker就把360桌面删了，一直很用好，直到有一天做软件安全测试：

群晖路径下的sys.sqlite保存了服务器连接地址 用户名 密码 同步目录列表 等信息，细思极恐。 

![Snipaste_2021-11-10_11-14-40](https://user-images.githubusercontent.com/22785084/141043790-14bb2e1f-dc84-43a4-a52f-d2f657c6dbbc.png)
![Snipaste_2021-11-10_11-16-09](https://user-images.githubusercontent.com/22785084/141043798-736a4cbc-406d-4cdc-bc4e-3bb22d216c0d.png)

**Comment by coodesker** [comment]
您好，麻烦您明确了问题再提issue，酷呆桌面是类explorer.exe，会加载电脑里注册的很多第三方模块，您先明确下是哪个模块做的，酷呆桌面本身没有获取任何隐私的东西，您也可以抓下网络访问看看有没有上传隐私。

**Comment by coodesker** [comment]
还麻烦您尽快明确是哪个模块做的给我们回复一下

**Comment by gdzjy** [comment]
我就是有疑问，所以提这issue，不确定是不是我的个例。

另外只对比了360桌面提取版，没有检测到要获取群晖数据库文件。

另外coodesker开启软件和关闭软件都有与服务器通信（360也是有）。本人技术有限不会解包，希望是检测版本的联网。
![Snipaste_2021-11-10_13-01-38](https://user-images.githubusercontent.com/22785084/141053468-3dc18a06-a11f-4308-b5fd-ac2582ef6e04.png)
[Uploading 360DesktopLite.zip…]()

**Comment by gdzjy** [comment]
我就是有疑问，所以提这issue，不确定是不是我的个例。

另外只对比了360桌面提取版，没有检测到要获取群晖数据库文件。

另外coodesker开启软件和关闭软件都有与服务器通信（360也是有）。本人技术有限不会解包，希望是检测版本的联网。
![Snipaste_2021-11-10_13-01-38](https://user-images.githubusercontent.com/22785084/141053468-3dc18a06-a11f-4308-b5fd-ac2582ef6e04.png)
