### ISSUE TITLE
1.0.0.36/1.0.0.38 was blocked by McAfee

### ISSUE THREAD

**Issue by bulldevil** [coodesker/coodesker-desktop#110]
Suspect type is:
JTI/Suspect.65770!9772e8cc541c
Revert to 1.0.0.32 and this warning was not occured.

**Comment by GXY2017** [comment]
agree. Also blocked by Windows Security
![image](https://user-images.githubusercontent.com/29757319/145405512-0b7ae1b5-1440-4923-af31-e3cca2ca09b7.png)

**Comment by bulldevil** [comment]
It seems that 1.0.1.1 fixed this
