### ISSUE TITLE
功能建议：盒子内文件排序方式

### ISSUE THREAD

**Issue by yfdyh000** [coodesker/coodesker-desktop#121]
似乎默认按文件名排序？能否支持多样的排序方式呢（正序/倒序，文件名/修改日期/创建日期/手动拖放，新增置顶/底...）。虽然用文件名前缀也能变相实现。
似乎是支持手动拖拽排序的，但好像没有还原（重新排序）的功能，以及比较容易误触为移动/用快捷方式打开。

**Comment by GoGoogle** [comment]
> 似乎默认按文件名排序？能否支持多样的排序方式呢（正序/倒序，文件名/修改日期/创建日期/手动拖放，新增置顶/底...）。虽然用文件名前缀也能变相实现。 似乎是支持手动拖拽排序的，但好像没有还原（重新排序）的功能，以及比较容易误触为移动/用快捷方式打开。

右键里面可以排序的

**Comment by yfdyh000** [comment]
> > 似乎默认按文件名排序？能否支持多样的排序方式呢（正序/倒序，文件名/修改日期/创建日期/手动拖放，新增置顶/底...）。虽然用文件名前缀也能变相实现。 似乎是支持手动拖拽排序的，但好像没有还原（重新排序）的功能，以及比较容易误触为移动/用快捷方式打开。
> 
> 右键里面可以排序的

还真是，天衣无缝，之前以为是系统原装菜单。谢谢。
