### ISSUE TITLE
建议：能添加个文件以列表形式呈现的功能么？

### ISSUE THREAD

**Issue by taco055** [coodesker/coodesker-desktop#122]

**Comment by taco055** [comment]
https://i.postimg.cc/7hs2s4wc/00bdff360eca37f767cc19b678f677e.png

**Comment by coodesker** [comment]
您好，已经支持了，盒子空白处右键菜单或者右上角点击菜单按钮，查看，列表显示

**Comment by taco055** [comment]
<a href='https://postimg.cc/DJFGbQkb' target='_blank'><img src='https://i.postimg.cc/DJFGbQkb/47c76270282b4562972580331695119.png' border='0' alt='47c76270282b4562972580331695119'/></a>

**Comment by coodesker** [comment]
选择截图里的第二个菜单项（查看(V)）,选择列表

**Comment by taco055** [comment]
好的，谢谢，原来和window的融合一起了，我以为是没有用的呢
