### ISSUE TITLE
建议：可选择以排列形式代替图标

### ISSUE THREAD

**Issue by LKthe7** [coodesker/coodesker-desktop#137]
一些文件的属性比如视频的品质会罗列在文件名上，导致文件名很长。对于整部剧集所在的映射盒子，以图标形式显示不仅找不到想要的文件而且文件名阅读困难。建议添加排列显示，排序方式从小到大或者可选。

**Comment by coodesker** [comment]
您指的是列表展示码？是支持列表显示的，盒子右上角点击菜单按钮，选择查看，选择列表显示。
