### ISSUE TITLE
组合盒子内标签无法自定义

### ISSUE THREAD

**Issue by bangwb** [coodesker/coodesker-desktop#14]
组合盒子模式时
1、标签顺序无法调整
2、标签无法重命名

**Comment by coodesker** [comment]
您好，第一个问题已经解决了，点击标签，按ctrl+方向键可以改变标签顺序，您可以设置项里点击检查更新或者直接下载覆盖安装https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.7/coodesker_1.0.0.7.exe
第二个问题，外网版本就支持的，点击标签，双击标题栏修改标题后会同步到标签。

**Comment by coodesker** [comment]
fixed
