### ISSUE TITLE
通过快捷键弹出那个页面，能否自定义目录布局？

### ISSUE THREAD

**Issue by godefy** [coodesker/coodesker-desktop#163]
目前快捷键调出那个盒子，都是一些系统的目录，非常的凌乱，而且大多数用不上，不太实用。
不知道能否自定义这个面板的每一个目录？

**Comment by coodesker** [comment]
在置顶盒子右上角点击菜单按钮，选择解散映射盒子或者添加映射盒子可以自定义。
