### ISSUE TITLE
1.0.0.8双屏的副屏文件的分辨率存在异常

### ISSUE THREAD

**Issue by HanZhang1995** [coodesker/coodesker-desktop#17]
1.0.0.8双屏的副屏文件的分辨率存在异常
这是主屏![image](https://user-images.githubusercontent.com/41636685/100576598-68c6f380-3319-11eb-8398-e265f9f4b5ac.png)
这是副屏![image](https://user-images.githubusercontent.com/41636685/100576572-5c429b00-3319-11eb-8e12-1c268d3e599b.png)

**Comment by HanZhang1995** [comment]
副屏的图标会更大一些

**Comment by coodesker** [comment]
您好，这个问题已经修复，下一版很快会出来

**Comment by coodesker** [comment]
您好，问题已经修复，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.9/coodesker_1.0.0.9.exe
