### ISSUE TITLE
Coodesker Website error.

### ISSUE THREAD

**Issue by Mikachu2333** [coodesker/coodesker-desktop#175]
![图片](https://user-images.githubusercontent.com/63829496/173482435-b56d0af7-e75a-4cd6-aa87-6ad060d7cf22.png)

除河北保定外均无法访问

**Comment by coodesker** [comment]
官网已经恢复

**Comment by Mikachu2333** [comment]
收到

**Comment by Mikachu2333** [comment]
发现bug
![图片](https://user-images.githubusercontent.com/63829496/175817163-7cbbbaa1-c68d-48a1-81ff-490ac54fe1d3.png)
