### ISSUE TITLE
能否通过热键将整个桌面的盒子置顶？

### ISSUE THREAD

**Issue by kickTiger** [coodesker/coodesker-desktop#179]
### 使用情境：
如题，编辑文件的时候，需要查找桌面的内容，**需要回到桌面**。
然后在一个个切换打开过的应用，很是麻烦。

### 实现功能：是否可以将桌面呼出？
能否将一次性将桌面呼出并置顶，类似于现在的置顶盒子。
但是目前的置顶盒子还需要单独在添加一次，非常不方便。

**Comment by coodesker** [comment]
您好，最新版1.0.2.7已经支持，您可以下载试下

**Comment by kickTiger** [comment]
> 您好，最新版1.0.2.7已经支持，您可以下载试下

感谢作者大佬，这么快就上线新功能，使用后反馈如下：

## 使用情况
可以通过热键呼出桌面了，但是有一点点问题，
- 1，热键呼出桌面后，只有一个框的内容，然后其他的内容没有在框里，不能显示。
- 2，在桌面的时候，呼出了桌面，显示只有一个框的内容，其他的图标被打散了。取消呼出桌面又开始正常。

## 建议改进
- 1，修复呼出桌面后不显示其他内容框。
- 2，注意双屏显示器使用的桌面，第二注意高分辨率显示器缩放显示，会让呼出的桌面文件错位。

谢谢老板！

**Comment by coodesker** [comment]
最新版1.0.2.8已经优化

**Comment by kickTiger** [comment]
> 最新版1.0.2.8已经优化

第一时间更新了，目前非常完美，上面提到的所有问题都已经修复！
感谢作者大大的辛苦！
