### ISSUE TITLE
更新卡半天,关了没反应

### ISSUE THREAD

**Issue by Zxingw** [coodesker/coodesker-desktop#18]
点击检查更新,更新了半天卡差不多70%吧,然后把更新 x 掉以后,整个应用都没办法点击了,bug挺多

**Comment by coodesker** [comment]
您好，bug已复现，会尽快在下一版本中修复，发版后会第一时间通知您，您也可以加群方便沟通，qq群：729581290

**Comment by coodesker** [comment]
您好，新版已经解决，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.10/coodesker_1.0.0.10.exe
