### ISSUE TITLE
win11快速访问中的文件夹会出现在桌面上，且无法删除

### ISSUE THREAD

**Issue by piaogewala** [coodesker/coodesker-desktop#185]
右键属性会跳转到设置的个性化界面[https://s2.loli.net/2022/06/27/qlWr5NovbAB3xcU.png](url)
[https://s2.loli.net/2022/06/27/OfyALsgduN2bwan.png](url)
[https://s2.loli.net/2022/06/27/w3ZM7h6fWmUFpcq.png](url)

**Comment by amobaishi** [comment]
同样是这个问题，貌似我是升级25145才出现的，之前在22621没这个问题

**Comment by piaogewala** [comment]
目前我的系统版本是25145.1011，之前使用腾讯桌面整理也有类似问题

**Comment by coodesker** [comment]
目前该问题已经修复，可以加群获取内测版
