### ISSUE TITLE
疑问：映射盒子和普通盒子的优先级？

### ISSUE THREAD

**Issue by D9Lose** [coodesker/coodesker-desktop#186]
创建了映射盒子后，依然会优先整理到普通盒子里去。
目前的使用环境是C盘容量小，D、E盘有剩余空间
需求是希望把文件映射到D、E盘里，不占用C盘空间而又能在桌面上快速整理，寻找文件。新增的文件整理也进入到映射盒子里

**Comment by coodesker** [comment]
需要在设置项的整理规则里设置，规则越靠上优先级越高
