### ISSUE TITLE
桌面快捷方式右键菜单不一样是怎么回事

### ISSUE THREAD

**Issue by oooopsr** [coodesker/coodesker-desktop#19]
![Snipaste_2020-12-04_01-13-37](https://user-images.githubusercontent.com/46592890/101065184-cf753700-35cf-11eb-97ba-a83aef5c4adc.jpg)
本来想固定到开始菜单，但是有些应用快捷方式右键后是没有这个选项的，望修复！

**Comment by coodesker** [comment]
谢谢您的反馈，我们正在尝试修复此问题

**Comment by coodesker** [comment]
您好，问题已经修复，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.9/coodesker_1.0.0.9.exe
