### ISSUE TITLE
盒子拖动大小，盒子提示文字重影

### ISSUE THREAD

**Issue by duanluan** [coodesker/coodesker-desktop#2]
环境：Windows 10 专业工作站版 2004 19041.572
重现：新建盒子，**快速**拖动大小
![image](https://user-images.githubusercontent.com/14957667/97823096-e4218f00-1cf2-11eb-96a0-9a4626e59c5c.png)

**Comment by coodesker** [comment]
> 环境：Windows 10 专业工作站版 2004 19041.572
> 重现：新建盒子，**快速**拖动大小
> ![image](https://user-images.githubusercontent.com/14957667/97823096-e4218f00-1cf2-11eb-96a0-9a4626e59c5c.png)

您好，我们尝试复现这个问题，但是没有复现，方便提供一个联系方式吗，我们工程师远程看下

**Comment by duanluan** [comment]
> > 环境：Windows 10 专业工作站版 2004 19041.572
> > 重现：新建盒子，**快速**拖动大小
> > ![image](https://user-images.githubusercontent.com/14957667/97823096-e4218f00-1cf2-11eb-96a0-9a4626e59c5c.png)
> 
> 您好，我们尝试复现这个问题，但是没有复现，方便提供一个联系方式吗，我们工程师远程看下

建个交流群吧，小问题比较多暂时没用了

**Comment by coodesker** [comment]
qq群号：729581290
