### ISSUE TITLE
Why do Windows defender report it as some kind of virus? 

### ISSUE THREAD

**Issue by GOCUP40** [coodesker/coodesker-desktop#20]
It makes me unable to install coodesker on my PC runnig with win10 64bit

**Comment by coodesker** [comment]
We have fixed this issue. https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.19

**Comment by l00c00l** [comment]
I get this in win10 this day:
威胁文件：CooDesker-x64.exe
病毒类型：代码混淆器(HVM:VirTool/EmulEvader.z)（行为沙盒〕
威胁描还：过代码变形反跟踪、反虚拟机等技术手段，专门被病毒用来与安全件进行技术对抗的
恶意代码类型。

**Comment by l00c00l** [comment]
Coodesker-Portable-x64_1.0.0.22\CooDesker-x64.exe
