### ISSUE TITLE
1、显示置顶盒子希望可以指定快捷键；2、置顶桌面希望可以把盒子也置顶

### ISSUE THREAD

**Issue by paiguFK** [coodesker/coodesker-desktop#204]
1、这个功能只能在桌面右键拉起，这样其实跟到桌面打开我的电脑操作次数差不多，不够便捷
2、置顶桌面后盒子也跟着置顶会更加便捷，因为在桌面增加盒子是为了桌面便捷，然后置顶桌面带上盒子的话会锦上添花

**Comment by coodesker** [comment]
您好，最新版1.0.2.8都支持了，您可以从官网下载
