### ISSUE TITLE
一点简单的建议

### ISSUE THREAD

**Issue by Jack6811** [coodesker/coodesker-desktop#23]
可不可以添加一种把现在的桌面布局以文件形式导出，防止因为手残导致布局失效或因为进程被杀掉导致的缓存错误
就是相当于把我目前规划好的哪个文件在哪个盒子进行导出与导入，方便以外时恢复

**Comment by coodesker** [comment]
您好，后期会在菜单中添加入口，目前您还有一个方法就是，在windows窗口中打开路径%appdata%/coodesker/cache，目录下有个desk.cache文件就是桌面布局的缓存，您可以拷贝出来备份下，新安装后，先退出酷呆桌面，然后将该文件放到该目录下，重新启动酷呆桌面就可以了。

**Comment by coodesker** [comment]
您好，新版已经支持备份功能，在桌面空白处右键菜单，选择酷呆桌面，桌面备份即可；您可以在设置里检查更新一下，或者直接下载覆盖安装https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.11/coodesker_1.0.0.11.exe

**Comment by coodesker** [comment]
欢迎加群交流，qq群：729581290
