### ISSUE TITLE
果然还是跟360和腾讯桌面一样没法使用ctrl+shift+N新建文件夹。

### ISSUE THREAD

**Issue by strongshuai** [coodesker/coodesker-desktop#24]
我不知道这种桌面软件原理，但是我猜这类型的软件是不是都是一样，再原本的win默认的桌面上盖一层模拟的桌面，也就是我们看到的APP整理后的桌面，在模拟后的桌面空白处的右键菜单这些都是模拟win桌面的右键菜单的吧，以至于一些不常见的功能没添加进入，比如我标题里提到的新建桌面快捷键。

如果是的话，难道就没有单纯的在win默认桌面上，只添加整理小方盒的软件吗，我不要全部覆盖掉默认桌面，然后你在模拟个跟默认桌面差不多的桌面出来，因为崩溃APP的时候是整个桌面全白了。

不知道是不是我提到的想法没法实现。

**Comment by coodesker** [comment]
您好，新版已经支持了快捷键，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.30/Coodesker-x64_1.0.0.30.exe
