### ISSUE TITLE
创建映射盒子失效

### ISSUE THREAD

**Issue by LiuFu2014** [coodesker/coodesker-desktop#25]
在创建映射盒子后，映射盒子可以映射到文件夹中的内容：
![image](https://user-images.githubusercontent.com/9976611/101326235-f2416d00-38a7-11eb-9ba9-6cc8f13cbe96.png)
在我进行手动解散盒子后，再次进行映射，则无法映射到文件夹中的内容.
**解散**
![image](https://user-images.githubusercontent.com/9976611/101326329-10a76880-38a8-11eb-9edc-185830d28330.png)
**解散后再次创建**：
![image](https://user-images.githubusercontent.com/9976611/101326392-274dbf80-38a8-11eb-9864-2765856217a6.png)
此时

**Comment by LiuFu2014** [comment]
需要重启程序才能解决这本问题

**Comment by coodesker** [comment]
感谢反馈，已经定位到问题，下一版本会修复。

**Comment by coodesker** [comment]
您好，问题已经修复，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.9/coodesker_1.0.0.9.exe

**Comment by LiuFu2014** [comment]
真棒
