### ISSUE TITLE
重启后没有任何文字显示

### ISSUE THREAD

**Issue by lny161224** [coodesker/coodesker-desktop#26]
![Uploading image.png…]()

**Comment by coodesker** [comment]
您好，我们的qq群号：729581290，您可以加一下，详细描述下问题。

**Comment by coodesker** [comment]
您好，最新版应该已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.15/coodesker_1.0.0.15.exe
