### ISSUE TITLE
升级最新版后被卡巴杀了

### ISSUE THREAD

**Issue by zllx666** [coodesker/coodesker-desktop#260]
下面是卡巴的提示：
Event: Malicious object detected

Application name: taskhostw.exe
Application path: C:\Windows\System32
Component: File Anti-Virus
Result description: Detected
Type: Trojan
Name: UDS:Backdoor.Win32.Androm
Precision: Exactly
Threat level: High
Object type: File
Object name: coodesker-x64.exe
Object path: C:\Users\zhaox\AppData\Roaming\Coodesker
MD5 of an object: 3107E5F1C8BF0FBCFF2EDF102B2507B0
Reason: Cloud Protection

**Comment by coodesker** [comment]
请放心使用，新版加了开机服务加速启动酷呆，由于酷呆没有签名，所以被误报。

**Comment by zllx666** [comment]
好的 谢谢
