### ISSUE TITLE
Use hardware acceleration when available issue

### ISSUE THREAD

**Issue by discmis** [coodesker/coodesker-desktop#27]
NVIDIA GeForce MX130 
Drivers Version 457.51
system win10 1909(OS 組建18363.1139)
開用Use hardware acceleration when available，桌面Icon都會消失無法顯示出來
關閉Use hardware acceleration when available，就可正常

**Comment by coodesker** [comment]
hi boss，new version has solved this issue，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.13/coodesker_1.0.0.13.exe
