### ISSUE TITLE
将图标拖进盒子后，盒子无法拖拽改变位置

### ISSUE THREAD

**Issue by duanluan** [coodesker/coodesker-desktop#3]
环境：Windows 10 专业工作站版 2004 19041.572
重现：将多个图标拖动进盒子后，盒子无法拖拽，需要改变盒子大小后才可以重新拖拽

**Comment by coodesker** [comment]
> 环境：Windows 10 专业工作站版 2004 19041.572
> 重现：将多个图标拖动进盒子后，盒子无法拖拽，需要改变盒子大小后才可以重新拖拽

您好，谢谢您的反馈，下一版1.0.0.4会修改这个问题

**Comment by coodesker** [comment]
v1.0.0.5 fixed this issue
