### ISSUE TITLE
win10系统下自带防火墙与卡巴斯基防火墙都报木马病毒？

### ISSUE THREAD

**Issue by digiw** [coodesker/coodesker-desktop#30]
卡巴斯基检测到: HEUR:Trojan.Win32.Scar.gen
微软安全中心检测到：Trojan:Win32/Wacatac.D7lml

**Comment by coodesker** [comment]
您好，由于我们的文件没有签名，所以被爆毒了，您可以放行就可以了，签名的问题我们正在处理。

**Comment by Cloud33** [comment]
Is there any progress

**Comment by bulldevil** [comment]
Any progress?

**Comment by NBSOD** [comment]
So this software is stop update? Still have this warning in Windwos 10 20H2

**Comment by chezhiping** [comment]
> So this software is stop update? Still have this warning in Windwos 10 20H2

Sorry， We're having some problems in signature，but we have optimized the setup file,  and also support portable, it will be released as soon as possible.

**Comment by coodesker** [comment]
> So this software is stop update? Still have this warning in Windwos 10 20H2

Sorry， We're having some problems in signature，but we have optimized the setup file,  and also support portable, it will be released as soon as possible.

**Comment by coodesker** [comment]
> Any progress?

Sorry， We're having some problems in signature，but we have optimized the setup file,  and also support portable, it will be released as soon as possible.

**Comment by coodesker** [comment]
> Is there any progress

Sorry， We're having some problems in signature，but we have optimized the setup file,  and also support portable, it will be released as soon as possible.

**Comment by bulldevil** [comment]
> > Any progress?
> 
> Sorry， We're having some problems in signature，but we have optimized the setup file, and also support portable, it will be released as soon as possible.

Nice, find portable package in 1.0.0.17. It's more stable than before.

**Comment by yuukoamamiya** [comment]
我也有这个问题，但是这个问题只有安装版有，绿色版可以直接运行不报毒……

**Comment by coodesker** [comment]
> 我也有这个问题，但是这个问题只有安装版有，绿色版可以直接运行不报毒……

您好，我们用nsis打包工具打的包，不知道为什么会被报毒，我们现在已经在开发自己的打包工具，很快会发版，您可以先用免安装版https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.18/Coodesker-Portable-x64_1.0.0.18.zip

**Comment by coodesker** [comment]
We have fixed this issue，https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.19
