### ISSUE TITLE
建议双击时，执行展开操作而不是重命名操作

### ISSUE THREAD

**Issue by LiuFu2014** [coodesker/coodesker-desktop#31]
1.如图，在进行双击时，默认会进行重命名操作。
![image](https://user-images.githubusercontent.com/9976611/101599976-a4f30600-3a35-11eb-84ae-051276d8a8ec.png)
2.实际，我们更多的是想进行展开操作，而不是重命名，重命名的操作次数原低于我们展开面板的操作。而需要展开是，必须去点击下拉箭头，而由于透明的面板，在背景较暗时，往往很不方便找到这个下拉箭头

**Comment by coodesker** [comment]
感谢您的建议，我们下一版会把双击在标题文字时保持重命名操作，而双击在中间空白处时执行展开操作，其它建议您可以加群方便沟通，qq群：729581290

**Comment by coodesker** [comment]
您好，新版已经解决，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.10/coodesker_1.0.0.10.exe
