### ISSUE TITLE
View internal files when clicking on a folder.

### ISSUE THREAD

**Issue by caesar440315** [coodesker/coodesker-desktop#33]
Clicking on a folder does not open the explorer, but turns the fence into files inside the folder.

If you've used Fences, you know about this feature, is it possible?

**Comment by coodesker** [comment]
Good idea，it will coming in next version.

**Comment by coodesker** [comment]
New version support this issue，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.10/coodesker_1.0.0.10.exe
