### ISSUE TITLE
建议添加鼠标悬停展开盒子功能

### ISSUE THREAD

**Issue by ibin7777** [coodesker/coodesker-desktop#35]
可以把这个跟[issue31](https://github.com/coodesker/coodesker-desktop/issues/31)集合起来
就像以前的搜狗或者腾讯桌面一样，鼠标移动到闭合的盒子上时自动展开，鼠标离开这个盒子后自动闭合，这样子能够大幅提高效率
我以前用腾讯那款，喜欢把回收站放到快捷方式盒子里面
需要删除的东西就直接拖拽到盒子上使其展开，继而放到回收站里，鼠标移开之后盒子自动闭合，非常方便整洁
![image](https://user-images.githubusercontent.com/64576479/101977752-db758e80-3c8a-11eb-89d6-ebda6212b590.png)

**Comment by coodesker** [comment]
您好，该功能正在开发中，近期会发一版，其它建议您可以加群方便沟通，qq群：729581290

**Comment by coodesker** [comment]
您好新版已经解决，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.10/coodesker_1.0.0.10.exe
