### ISSUE TITLE
桌面上剪切文件,文件图标不会变虚

### ISSUE THREAD

**Issue by da-ye-wei-teng** [coodesker/coodesker-desktop#37]
而且有时候在桌面上,快捷键会不好用,比如F2,ctrl+x,ctrl+c

**Comment by coodesker** [comment]
您好，图标的问题下一版排期解决中，快捷键的问题已经解决了，可以在设置中检查更新下

**Comment by coodesker** [comment]
您好，图标问题已经解决，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.12/coodesker_1.0.0.12.exe
