### ISSUE TITLE
硬盘重新分盘后，原映射盒子无法解散

### ISSUE THREAD

**Issue by Dawn-Newbie** [coodesker/coodesker-desktop#40]
对硬盘重新划分了逻辑盘，原映射盒子所映射文件盘符丢失，现无法解散映射盒子

**Comment by coodesker** [comment]
您好，问题已经解决，您可以在设置里检查更新一下，或者直接下载覆盖安装https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.11/coodesker_1.0.0.11.exe

**Comment by coodesker** [comment]
欢迎加群交流，qq群：729581290
