### ISSUE TITLE
#Bug coodesker自动打开Show animations in Windows选项，且手动关闭后将不显示桌面壁纸

### ISSUE THREAD

**Issue by b4imetu** [coodesker/coodesker-desktop#42]
coodesker自动打开 `在Windows中显示动画特效选项` / `Show animations in Windows` 选项，此选项我一般关闭以优化图形性能，开启后很不习惯。

手动关闭后将不显示桌面壁纸，希望新版本修复这个Bug。

![image](https://user-images.githubusercontent.com/41535001/103972087-25577480-5164-11eb-8fd7-bfab22c61f11.png)

**Comment by coodesker** [comment]
您好，问题已经解决，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.12/coodesker_1.0.0.12.exe
