### ISSUE TITLE
双屏显示控制问题

### ISSUE THREAD

**Issue by workhd** [coodesker/coodesker-desktop#44]
创建了多个盒子，使用的是笔记本，外接了一个显示器，两个屏幕一起用。一天偶然把一个盒子 拖到 外接显示屏上，发现就没法拖回去了。在外接显示屏上也无法调整大小 无法 删除

**Comment by coodesker** [comment]
您好，您应该是使用的老版本，设置对话框里点击关于，检查更新成最新版应该就可以了
