### ISSUE TITLE
盒子里面的文件如果很多 使用滚轮下拉没反应。

### ISSUE THREAD

**Issue by HankMo** [coodesker/coodesker-desktop#47]
![image](https://user-images.githubusercontent.com/60347960/107139085-5e743780-6910-11eb-99bc-2280b47f8987.png)

**Comment by coodesker** [comment]
您好，请问您用的是什么版本呢，我们没有复现这个问题。

**Comment by HankMo** [comment]
最新版本0.14

**Comment by HankMo** [comment]
是不是和别的软件冲突了   我怀疑MyDock  和  Wallpaper Engine  但是我不能卸载 来验证，因为我花了好大的力气才配置好我喜欢的样子。

**Comment by coodesker** [comment]
应该不是，您盒子里大约多少个文件？

**Comment by HankMo** [comment]
不到50个

**Comment by HankMo** [comment]
每次都要动下盒子大小，才可以正常使用滚轮下滑，我的系统是win10 20H2

**Comment by HankMo** [comment]
我刚才 有看了下  只有快捷方式盒子里面的才会这样 别的 盒子 正常

**Comment by coodesker** [comment]
我们明天尝试快捷方式盒子试下，您可以加群沟通，qq群：729581290

**Comment by coodesker** [comment]
最新版已经解决了该问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.15/coodesker_1.0.0.15.exe
