### ISSUE TITLE
win10 的defender报毒

### ISSUE THREAD

**Issue by zhanghuan66** [coodesker/coodesker-desktop#50]
刚刚下载下来就被删除了

**Comment by coodesker** [comment]
您好，我们用nsis打包工具打的包，不知道为什么会被报毒，我们现在已经在开发自己的打包工具，很快会发版，您可以先用免安装版https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.18/Coodesker-Portable-x64_1.0.0.18.zip

**Comment by coodesker** [comment]
您好，我们已经更换打包方式，应该解决了此问题，https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.19
