### ISSUE TITLE
希望可以选择性把“整理桌面”从右键菜单中去除

### ISSUE THREAD

**Issue by Karveit** [coodesker/coodesker-desktop#51]
右键菜单中的“整理桌面”经常被误点到，导致排版错乱，希望可以选择性把“整理桌面”从右键菜单中去除。

**Comment by coodesker** [comment]
您好，已经把整理桌面移到菜单里面了，您可以尝试下。https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.22/Coodesker-x64_1.0.0.22.exe
