### ISSUE TITLE
使用小米远程管理功能将文件拖拽到桌面会删除文件且桌面没有文件

### ISSUE THREAD

**Issue by vaini5** [coodesker/coodesker-desktop#52]
我使用小米远程管理功能、FTP类型、将手机里面的视频拖拽至桌面、会删除手机中的文件、且桌面上也没有文件。导致数据丢失，将coodesker软件关闭再测试 会默认将手机文件复制到桌面。 现在手机文件丢失了

**Comment by coodesker** [comment]
抱歉给您带来不便，我们正在尝试复现解决该问题

**Comment by coodesker** [comment]
您好，新版已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.34/Coodesker-x64_1.0.0.34.exe
