### ISSUE TITLE
无法从 VMWare 虚拟机中复制文件到桌面

### ISSUE THREAD

**Issue by thecodehustler** [coodesker/coodesker-desktop#63]
在虚拟机中 Ctrl+C 复制文件，转到宿主机桌面上有粘贴选项，无法粘贴文件。

- VMWare 版本：16.1.1
- 宿主机：Windows 10 20H2
- 虚拟机：Windows 7，已安装 VMWare Tools

**Comment by coodesker** [comment]
您好，新版已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.31/Coodesker-x64_1.0.0.31.exe
