### ISSUE TITLE
文件夹映射 双击响应 问题

### ISSUE THREAD

**Issue by Kayer9328** [coodesker/coodesker-desktop#64]
你好！文件夹映射的盒子里 双击文件夹是否可以直接打开Windows资源管理器，因为跳转之后，会以小图标显示文件里的内容，设定的格子比较小的话，查看起来不太方便

**Comment by coodesker** [comment]
您好，新版已经支持了，在设置项里可以取消勾选，新版https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21

**Comment by Kayer9328** [comment]
看到了，是可以的，谢谢！

**Comment by Kayer9328** [comment]
看到了，是可以的 ，谢谢啦！

**Comment by 00LT00** [comment]
> 您好，新版已经支持了，在设置项里可以取消勾选，新版https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21

你好，我这边用的是files作为explorer替代，无论我是否勾选，都是在files中打开的，不知道是否有适配的计划
