### ISSUE TITLE
每次重启桌面，排列的盒子都会改变原有格式

### ISSUE THREAD

**Issue by jidesheng6** [coodesker/coodesker-desktop#66]
语言描述可能不清晰，我给出两个图片URL，麻烦看一下

重启之前设置好的盒子格式：https://imgtu.com/i/2CwW8O

重启之后被改变的样子：https://www.hualigs.cn/image/60aefafdaafff.jpg

另外还有一个问题：若在设置好盒子格式之后，软件突然崩溃，下次启动的时候盒子设置全部失效，需要重新排列。

**Comment by coodesker** [comment]
您好，新版应该已经解决了这个问题，您可以尝试一下新版https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21
