### ISSUE TITLE
【功能】不支持壁纸幻灯片放映， 盒子里面的快捷方式不支持拖拽到指定位置

### ISSUE THREAD

**Issue by fxxf1111** [coodesker/coodesker-desktop#69]
不能更改壁纸这点有点遗憾。

盒子里面的快捷方式不支持拖拽到指定位置，强制自动排序？希望能手动整理

**Comment by coodesker** [comment]
您好，幻灯片放映已经解决了，新版https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21，您能具体描述下“盒子里面的快捷方式不支持拖拽到指定位置”这个问题如何复现吗？

**Comment by fxxf1111** [comment]
> 
> 
> 您好，幻灯片放映已经解决了，新版[https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21，您能具体描述下“盒子里面的快捷方式不支持拖拽到指定位置”这个问题如何复现吗？](https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21%EF%BC%8C%E6%82%A8%E8%83%BD%E5%85%B7%E4%BD%93%E6%8F%8F%E8%BF%B0%E4%B8%8B%E2%80%9C%E7%9B%92%E5%AD%90%E9%87%8C%E9%9D%A2%E7%9A%84%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F%E4%B8%8D%E6%94%AF%E6%8C%81%E6%8B%96%E6%8B%BD%E5%88%B0%E6%8C%87%E5%AE%9A%E4%BD%8D%E7%BD%AE%E2%80%9D%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E5%A6%82%E4%BD%95%E5%A4%8D%E7%8E%B0%E5%90%97%EF%BC%9F)

盒子里面的快捷方式不支持拖拽到指定位置----类似与桌面自动排列图标与非自动排列图标，希望盒子里的图标可以随意摆放。如图所示：
![捕获](https://user-images.githubusercontent.com/48472903/121710911-a00a2e80-cb0c-11eb-8564-aa33f972c58e.PNG)
