### ISSUE TITLE
盒子展开问题

### ISSUE THREAD

**Issue by Beansdz** [coodesker/coodesker-desktop#70]
如果我把A盒子折叠之后，将一个A盒子拉大边缘并触碰另外一个B盒子（无论B是展开的还是折叠的），会让A盒子无法展开，必须解散A盒子重新建立

**Comment by coodesker** [comment]
感谢反馈并提供复现方法，问题我们已经解决了，新版连接https://github.com/coodesker/coodesker-desktop/releases/tag/v1.0.0.21
