### ISSUE TITLE
新版的软件貌似保留不了桌面的盒子布局（指位置大小之类的）

### ISSUE THREAD

**Issue by AntaresShao** [coodesker/coodesker-desktop#71]
个人改了盒子的大小和位置并进行了锁定，把每个盒子都贴着另一个放的，边也都是调成了等宽的。然后等再开机之后就有4/6的盒子被打乱了，其中有两个还几乎叠在了一起，然后我移开的时候他们就一下子合成一个盒子了，然后这四个盒子的大小也变成了刚更新完之后最开始的大小。只有两个最靠边的盒子没有变位置和大小。总之就是有点混乱。

**Comment by coodesker** [comment]
您好，我们更新了一下1.0.0.21版本，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.21/Coodesker-x64_1.0.0.21.exe，您可以下载覆盖安装试下，有问题欢迎您随时联系我们，qq:729581290

**Comment by AntaresShao** [comment]
> 您好，我们更新了一下1.0.0.21版本，[https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.21/Coodesker-x64_1.0.0.21.exe，您可以下载覆盖安装试下，有问题欢迎您随时联系我们，qq:729581290](https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.21/Coodesker-x64_1.0.0.21.exe%EF%BC%8C%E6%82%A8%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E8%A6%86%E7%9B%96%E5%AE%89%E8%A3%85%E8%AF%95%E4%B8%8B%EF%BC%8C%E6%9C%89%E9%97%AE%E9%A2%98%E6%AC%A2%E8%BF%8E%E6%82%A8%E9%9A%8F%E6%97%B6%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC%EF%BC%8Cqq:729581290)

@coodesker 我现在用的就是1.0.0.21。😂

**Comment by coodesker** [comment]
是的，我们已经把服务器上的1.0.0.21版本替换了，您可以下载试下。

**Comment by AntaresShao** [comment]
> 是的，我们已经把服务器上的1.0.0.21版本替换了，您可以下载试下。

OK，问题解决了！感谢！
