### ISSUE TITLE
从版本16到21，窗口变得非常大

### ISSUE THREAD

**Issue by congmingyige** [coodesker/coodesker-desktop#72]
如图
![图片](https://user-images.githubusercontent.com/20537566/122369117-7f205e00-cf90-11eb-9a4e-72c3a7d94f22.png)

这是整个屏幕的一整个宽度
![图片](https://user-images.githubusercontent.com/20537566/122369355-b1ca5680-cf90-11eb-88a7-5801e40a0957.png)

**Comment by congmingyige** [comment]
请问怎么做？是否需要卸载尝试？

**Comment by congmingyige** [comment]
可能与这个相关，但是16版本没有这个问题。
比如调整为100%，内容的确会变小
![图片](https://user-images.githubusercontent.com/20537566/122370208-767c5780-cf91-11eb-9a0a-d5457704ed67.png)

**Comment by coodesker** [comment]
您好，因为21版本适配了多屏dpi，会导致老版本盒子升级到新版本后会变大，您重新调整一下盒子大小，之后就不会再有问题了。

**Comment by congmingyige** [comment]
好的，谢谢！非常及时的回复！
