### ISSUE TITLE
Win10系统，设置了开机启动，从显示桌面到整理好桌面至少5秒+

### ISSUE THREAD

**Issue by lixiao0618** [coodesker/coodesker-desktop#74]
Win10系统，设置了开机启动，从显示桌面到整理好桌面至少5秒+，希望优化一下啊。已经设置了硬件加速

**Comment by powertowill** [comment]
同样希望优化一下开机启动的速度

**Comment by coodesker** [comment]
您好，新版已经添加了计划任务启动，速度比之前快很多，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.31/Coodesker-x64_1.0.0.31.exe
