### ISSUE TITLE
打开文件对话框中复制粘贴快捷键失效

### ISSUE THREAD

**Issue by williamli21** [coodesker/coodesker-desktop#75]
当某些软件用到打开对话框时，我事先对桌面的文件用ctrl+C快捷键获取路径，再粘贴会没有用。但是如果我用右键的复制功能再粘贴是可以正常粘贴到打开对话框的。

同时确认用快捷键复制粘贴文件的功能是没问题的。

所以问题应该是只针对文件对话框中的复制粘贴功能失效了。

**Comment by coodesker** [comment]
您好，新版已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.31/Coodesker-x64_1.0.0.31.exe
