### ISSUE TITLE
提高组合盒子的自由度

### ISSUE THREAD

**Issue by yuzhen1024** [coodesker/coodesker-desktop#76]
1. 允许组合盒子之间可以调换位置。
2. 允许只拆解其中的一个盒子，避免为了拆一个而不得不全部拆散。

**Comment by coodesker** [comment]
您好，点击标签后，按住ctrl+左右方向键可以改变标签顺序，盒子菜单里支持解散一个盒子。

**Comment by yuzhen1024** [comment]
> 您好，点击标签后，按住ctrl+左右方向键可以改变标签顺序，盒子菜单里支持解散一个盒子。

太棒了

**Comment by starx1n9** [comment]
哇 简直发现新世界
