### ISSUE TITLE
无法识别主副屏 Unable to recognize the main and secondary screens.

### ISSUE THREAD

**Issue by snwjas** [coodesker/coodesker-desktop#77]
电脑主副屏显示选项为拓展时，在开机时桌面的东西会跑到副屏中去，关闭副屏投影，单独使用主屏显示，桌面的图标布局会被打乱。说明：主副屏显示分辨率一致，缩放一致。

When the display option of the main and secondary screens of the computer is extended, when the computer is turned on, things on the desktop will run to the secondary screen, turn off the secondary screen projection, and use the main screen display alone, and the layout of the desktop icons will be disrupted. Note: the main and secondary screen display resolution is consistent, and the zoom is consistent.

**Comment by coodesker** [comment]
您是什么版本？最新版应该已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.21/Coodesker-x64_1.0.0.21.exe

**Comment by snwjas** [comment]
> 您是什么版本？最新版应该已经解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.21/Coodesker-x64_1.0.0.21.exe

就是最新版本，1.0.0.21 x64，我是使用笔记本电脑外接屏幕的，然后外接的屏幕作为主屏，笔记本电脑的屏幕作为副屏。
我尝试了“显示设置-多显示器设置”那里轮换设置主副屏的[设为主显示器]，发现桌面并不会移到目前的主显示器中，而且在切换过程中，桌面布局会被打乱。

**Comment by coodesker** [comment]
您可以加群沟通，qq群：729581290

**Comment by coodesker** [comment]
您好，新版已经彻底解决了这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.25/Coodesker-x64_1.0.0.25.exe
