### ISSUE TITLE
盒子展开问题

### ISSUE THREAD

**Issue by Beansdz** [coodesker/coodesker-desktop#79]
如果把一个盒子折叠，在折叠状态下直接通过盒子边上的三条杠进行“创建盒子”操作，会导致这个折叠盒子无法展开，而且分离这个问题盒子出来的所有盒子也无法展开

**Comment by coodesker** [comment]
您好，23版本已经解决这个问题，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.23/Coodesker-x64_1.0.0.23.exe
