### ISSUE TITLE
更换显示器(高分->低分)后, 盒子不会自适应而导致在视野及可操作范围外

### ISSUE THREAD

**Issue by AuroraTea** [coodesker/coodesker-desktop#82]
更换显示器(高分->低分)后, 盒子不会自适应而导致在视野及可操作范围外

**Comment by coodesker** [comment]
您好，请问您是什么版本？新版可能已经解决了这个问题，如果是新版还是出现问题的话，能麻烦提供下更换前和更换后的截图吗？

**Comment by AuroraTea** [comment]
不好意思当时没更新到最新版就来提issue了, 更新后已经解决了, 之前是因为更新会卡进度条(如图)所以一直没有更新  
![quicker_071d4836-b0db-47b9-b99a-74585cd83bb0.png](https://i.loli.net/2021/07/24/7G3j4Qgykr9u8Bi.png)

**Comment by coodesker** [comment]
好的，从截图看您的版本很老了，新版也优化了下更新逻辑，有问题欢迎随时联系
