### ISSUE TITLE
资源管理器重启后酷呆桌面会彻底崩溃

### ISSUE THREAD

**Issue by LHT02** [coodesker/coodesker-desktop#85]
有的时候桌面图标多了桌面资源管理器会崩溃，然后酷呆桌面会留一个卡死的进程在后台，不会自动重启整理。
建议学下360的桌面助手，可以在资源管理器崩溃重启后重新自动进行加载

**Comment by coodesker** [comment]
您好23版本已经修改了这个bug，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.23/Coodesker-x64_1.0.0.23.exe
