### ISSUE TITLE
无法从“以前的版本”（PreviousVersions）中复制文件到桌面

### ISSUE THREAD

**Issue by Skies034** [coodesker/coodesker-desktop#86]
在文件夹中 Ctrl+C 复制文件，转到主机桌面上可以粘贴。
但在Window的以前的版本（PreviousVersions）中Ctrl+C 复制文件，转到主机桌面上有粘贴选项，但无法粘贴文件。

- 主机：Windows 10 21H1
- 以前的版本（PreviousVersions）的资料来源：虚拟机中（VMware ESX 4.0 Server）的FreeNAS（FreeNAS-11.3-U5）

**Comment by coodesker** [comment]
您好，新版已经解决，您可以试下，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.36/Coodesker-x64_1.0.0.36.exe
