### ISSUE TITLE
文字DPI变化

### ISSUE THREAD

**Issue by ZWolken** [coodesker/coodesker-desktop#89]
请问能否随系统设置改变程序运行后桌面所显示的文字大小？

如图：

程序运行前：

<img width="1280" alt="OFF" src="https://user-images.githubusercontent.com/76812845/131543130-377c7751-83af-4ebe-8da7-54d3a2c74f7c.png">

程序运行时：

<img width="1280" alt="ON" src="https://user-images.githubusercontent.com/76812845/131543140-9ed22944-8c97-4f08-b3c4-f772e90c4a15.png">

文字的字体字号粗细均无法改变导致较难认读。

补充：系统使用了 http://tatsu.life.coocan.jp/ 的 **No!! Meiryo UI** 工具更改了显示字体、字号以及粗细。

谢谢~

**Comment by ZWolken** [comment]
补充：系统使用了[http://tatsu.life.coocan.jp/](url)的**No!! Meiryo UI**工具更改了显示字体、字号以及粗细。

**Comment by coodesker** [comment]
您好，新版问题已经解决。
