### ISSUE TITLE
使用后QuickLook无法使用

### ISSUE THREAD

**Issue by Chaostrom** [coodesker/coodesker-desktop#9]
开发者你好，[Quicklook](https://github.com/QL-Win/QuickLook)按空格键可以预览文件内容，使用酷呆桌面后该功能无法使用

**Comment by S-Kee** [comment]
我也遇到了这个问题

**Comment by coodesker** [comment]
您好，新版已经兼容了quicklook，功能相比之前也有很大提升，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.30/Coodesker-x64_1.0.0.30.exe
