### ISSUE TITLE
拖放摆放图标位置时无法精确识别

### ISSUE THREAD

**Issue by GoGoogle** [coodesker/coodesker-desktop#92]
建议在拖动摆放位置的时候加入分隔符，不然真拖不到想要的位置

例如我要拖动图标A到BCD之间，顺序成为BACD，就非常不智能

**Comment by coodesker** [comment]
您好，感谢反馈，我们会排期解决。

**Comment by GoGoogle** [comment]
> 您好，感谢反馈，我们会排期解决。

可参考360桌面助手

**Comment by GoGoogle** [comment]
这个还没搞定吗？

**Comment by coodesker** [comment]
您好，这个1.0.0.36版本已经优化了，下周会发版

**Comment by GoGoogle** [comment]
期待这么一个大更新，感谢。

**Comment by GoGoogle** [comment]
我发现新版本只是有个禁止停放的提示图标，体验不佳，需要的是分隔线一样的那种提示，不是这样的禁止停放的提示

禁止停放的提示在把第三个图标拖至第一个时，就很不友好，根本不能精准定位。

如果是分割线的提示，这样的情况就可以在第一个图标左边出现分隔线，从而达到精准定位。

**Comment by coodesker** [comment]
您好，上一版主要支持了右键拖拽以及拖拽提示，定位光标的已经开发完成，光标与系统保持一致，下一版会带上。

**Comment by coodesker** [comment]
您好，定位光标版本已经发版，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.38/Coodesker-x64_1.0.0.38.exe

**Comment by GoGoogle** [comment]
已经在用了，谢谢支持。
