### ISSUE TITLE
右键拖动或拖动路径到桌面想形成快捷方式图标时的Bug

### ISSUE THREAD

**Issue by GoGoogle** [coodesker/coodesker-desktop#93]
这个Bug会很要命，你可以试试

**Comment by coodesker** [comment]
您好，新版1.0.0.36已经支持了右键拖拽，可以加qq群获取最新版本，729581290

**Comment by coodesker** [comment]
新版已经支持，https://github.com/coodesker/coodesker-desktop/releases/download/v1.0.0.36/Coodesker-x64_1.0.0.36.exe
